# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task001' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.9.0'

  # Pods for Task001

end
